// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using SecondBrain.Infrastructure.Data;

#nullable disable

namespace SecondBrain.Infrastructure.Migrations
{
    [DbContext(typeof(SecondBrainDbContext))]
    [Migration("20260615140840_LowerCaseTableName")]
    partial class LowerCaseTableName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SecondBrain.Core.Entities.ChunkTag", b =>
                {
                    b.Property<Guid>("ChunkId")
                        .HasColumnType("uuid")
                        .HasColumnName("chunkid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tagid");

                    b.HasKey("ChunkId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("chunktags");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.Contradiction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChunkAId")
                        .HasColumnType("uuid")
                        .HasColumnName("chunkaid");

                    b.Property<Guid>("ChunkBId")
                        .HasColumnType("uuid")
                        .HasColumnName("chunkbid");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detectedat");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("text")
                        .HasColumnName("resolutionnote");

                    b.Property<bool>("Resolved")
                        .HasColumnType("boolean")
                        .HasColumnName("resolved");

                    b.HasKey("Id");

                    b.HasIndex("ChunkAId");

                    b.HasIndex("ChunkBId");

                    b.ToTable("contradictions");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.IngestionJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ChunksCreated")
                        .HasColumnType("integer")
                        .HasColumnName("chunkscreated");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completedat");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("errormessage");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("sourceid");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("startedat");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.ToTable("ingestionjobs");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.KnowledgeChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessCount")
                        .HasColumnType("integer")
                        .HasColumnName("accesscount");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(768)")
                        .HasColumnName("embedding");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingestedat");

                    b.Property<DateTimeOffset?>("LastAccessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastaccessedat");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("sourceid");

                    b.HasKey("Id");

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("SourceId");

                    b.ToTable("knowledgechunks");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.Query", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<DateTimeOffset>("AskedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("askedat");

                    b.Property<string>("ModelUsed")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modelused");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.HasKey("Id");

                    b.ToTable("queries");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.QueryChunkLink", b =>
                {
                    b.Property<Guid>("QueryId")
                        .HasColumnType("uuid")
                        .HasColumnName("queryid");

                    b.Property<Guid>("ChunkId")
                        .HasColumnType("uuid")
                        .HasColumnName("chunkid");

                    b.Property<int>("RelevanceScore")
                        .HasColumnType("integer")
                        .HasColumnName("relevancescore");

                    b.HasKey("QueryId", "ChunkId");

                    b.HasIndex("ChunkId");

                    b.ToTable("querychunklinks");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingestedat");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publishedat");

                    b.PrimitiveCollection<string[]>("Tags")
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.ToTable("sources");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("tags");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.ChunkTag", b =>
                {
                    b.HasOne("SecondBrain.Core.Entities.KnowledgeChunk", "Chunk")
                        .WithMany("ChunkTags")
                        .HasForeignKey("ChunkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chunktags_knowledgechunks_chunkid");

                    b.HasOne("SecondBrain.Core.Entities.Tag", "Tag")
                        .WithMany("ChunkTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chunktags_tags_tagid");

                    b.Navigation("Chunk");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.Contradiction", b =>
                {
                    b.HasOne("SecondBrain.Core.Entities.KnowledgeChunk", "ChunkA")
                        .WithMany("ContradictionsA")
                        .HasForeignKey("ChunkAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contradictions_knowledgechunks_chunkaid");

                    b.HasOne("SecondBrain.Core.Entities.KnowledgeChunk", "ChunkB")
                        .WithMany("ContradictionsB")
                        .HasForeignKey("ChunkBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contradictions_knowledgechunks_chunkbid");

                    b.Navigation("ChunkA");

                    b.Navigation("ChunkB");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.IngestionJob", b =>
                {
                    b.HasOne("SecondBrain.Core.Entities.Source", "Source")
                        .WithMany("IngestionJobs")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ingestionjobs_sources_sourceid");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.KnowledgeChunk", b =>
                {
                    b.HasOne("SecondBrain.Core.Entities.Source", "Source")
                        .WithMany("KnowledgeChunks")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_knowledgechunks_sources_sourceid");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.QueryChunkLink", b =>
                {
                    b.HasOne("SecondBrain.Core.Entities.KnowledgeChunk", "Chunk")
                        .WithMany("QueryChunkLinks")
                        .HasForeignKey("ChunkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_querychunklinks_knowledgechunks_chunkid");

                    b.HasOne("SecondBrain.Core.Entities.Query", "Query")
                        .WithMany("QueryChunkLinks")
                        .HasForeignKey("QueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_querychunklinks_queries_queryid");

                    b.Navigation("Chunk");

                    b.Navigation("Query");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.KnowledgeChunk", b =>
                {
                    b.Navigation("ChunkTags");

                    b.Navigation("ContradictionsA");

                    b.Navigation("ContradictionsB");

                    b.Navigation("QueryChunkLinks");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.Query", b =>
                {
                    b.Navigation("QueryChunkLinks");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.Source", b =>
                {
                    b.Navigation("IngestionJobs");

                    b.Navigation("KnowledgeChunks");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.Tag", b =>
                {
                    b.Navigation("ChunkTags");
                });
#pragma warning restore 612, 618
        }
    }
}
