// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using SecondBrain.Infrastructure.Data;

#nullable disable

namespace SecondBrain.Infrastructure.Migrations
{
    [DbContext(typeof(SecondBrainDbContext))]
    [Migration("20260611123626_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SecondBrain.Core.Entities.ChunkTag", b =>
                {
                    b.Property<Guid>("ChunkId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("ChunkId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ChunkTags");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.Contradiction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChunkAId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChunkBId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("text");

                    b.Property<bool>("Resolved")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ChunkAId");

                    b.HasIndex("ChunkBId");

                    b.ToTable("Contradictions");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.IngestionJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChunksCreated")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.ToTable("IngestionJob");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.KnowledgeChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessCount")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(768)");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastAccessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("SourceId");

                    b.ToTable("KnowledgeChunks");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.Query", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("AskedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModelUsed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Queries");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.QueryChunkLink", b =>
                {
                    b.Property<Guid>("QueryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChunkId")
                        .HasColumnType("uuid");

                    b.Property<int>("RelevanceScore")
                        .HasColumnType("integer");

                    b.HasKey("QueryId", "ChunkId");

                    b.HasIndex("ChunkId");

                    b.ToTable("QueryChunkLinks");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string[]>("Tags")
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.ChunkTag", b =>
                {
                    b.HasOne("SecondBrain.Core.Entities.KnowledgeChunk", "Chunk")
                        .WithMany("ChunkTags")
                        .HasForeignKey("ChunkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecondBrain.Core.Entities.Tag", "Tag")
                        .WithMany("ChunkTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chunk");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.Contradiction", b =>
                {
                    b.HasOne("SecondBrain.Core.Entities.KnowledgeChunk", "ChunkA")
                        .WithMany("ContradictionsA")
                        .HasForeignKey("ChunkAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SecondBrain.Core.Entities.KnowledgeChunk", "ChunkB")
                        .WithMany("ContradictionsB")
                        .HasForeignKey("ChunkBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChunkA");

                    b.Navigation("ChunkB");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.IngestionJob", b =>
                {
                    b.HasOne("SecondBrain.Core.Entities.Source", "Source")
                        .WithMany("IngestionJobs")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.KnowledgeChunk", b =>
                {
                    b.HasOne("SecondBrain.Core.Entities.Source", "Source")
                        .WithMany("KnowledgeChunks")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.QueryChunkLink", b =>
                {
                    b.HasOne("SecondBrain.Core.Entities.KnowledgeChunk", "Chunk")
                        .WithMany("QueryChunkLinks")
                        .HasForeignKey("ChunkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecondBrain.Core.Entities.Query", "Query")
                        .WithMany("QueryChunkLinks")
                        .HasForeignKey("QueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chunk");

                    b.Navigation("Query");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.KnowledgeChunk", b =>
                {
                    b.Navigation("ChunkTags");

                    b.Navigation("ContradictionsA");

                    b.Navigation("ContradictionsB");

                    b.Navigation("QueryChunkLinks");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.Query", b =>
                {
                    b.Navigation("QueryChunkLinks");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.Source", b =>
                {
                    b.Navigation("IngestionJobs");

                    b.Navigation("KnowledgeChunks");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.Tag", b =>
                {
                    b.Navigation("ChunkTags");
                });
#pragma warning restore 612, 618
        }
    }
}
